spring.application.name=spring-basics-data
server.port=9985

#Profile
spring.profiles.active=dev


#springdoc.api-docs.path=/api-docs

#To access swagger URI
#http://localhost:9985/swagger-ui/index.html